### ISSUE TITLE
how to know self  user is active user ?

### ISSUE THREAD

**Issue by mobcoder-pankaj** [aws-samples/amazon-chime-sdk#104]

**Comment by xuesichao** [comment]
Hi @mobcoder-pankaj Sorry for late reply.

If you are using Amazon Chime SDK React Components Library, you could simply use the [`useActiveSpeakersState`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-useactivespeakersstate--page), and check if the self user id is in the returned array.
To get the self attendee id:
```tsx
const localAttendeeId =  meetingManager.meetingSession?.configuration.credentials?.attendeeId || null;
```

If you are using Amazon Chime SDK for JavaScript, you need to `subscribeToActiveSpeakerDetector` and check if self attendee id is in the returned array. Refer [User Case 12](https://github.com/aws/amazon-chime-sdk-js#audio)
To get the self attendee id
```js
const localAttendeeId =  meetingSession?.configuration.credentials?.attendeeId || null;
```

**Comment by xuesichao** [comment]
Close the issue for now. Feel free to reopen it if you have further questions.
