### ISSUE TITLE
Error when uploading linked template.yaml

### ISSUE THREAD

**Issue by albrich-me** [aws-samples/amazon-chime-sdk#126]
**Demo**
Amazon Chime SDK Chat Demo

**Describe the bug**
Downloading the linked template.yaml file vs. doing a git clone creates an error 

**To Reproduce**
1. Under Deploying the solution, right click on template.yaml in step 3 and select "Save Link As..."
2. Click on "Save"
3. Perform steps 1,2, and 3.
4. You will get the following error when you try to create the stack:  Template format error: YAML not well-formed. (line 149, column 65)

**Expected behavior**
If you perform the same procedure using the template.yaml downloaded using git clone, you do not get the error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 11.6.2
 - Browser Firefox 
 - Version 91.4.0esr

**Comment by michhyun1** [comment]
@albrich-me I dont think the "Save Link As" feature is downloading the template.yml the way that you expect it is. 

The only way to download that file is to clone the repo.
