### ISSUE TITLE
Registration Error Adding New User

### ISSUE THREAD

**Issue by albrich-me** [aws-samples/amazon-chime-sdk#127]
**Demo**
Amazon Chime SDK Chat Demo
**Describe the bug**
When adding a new user I get a Registration Error.

**To Reproduce**
1. Under "Cognito User Pools" perform steps 1-3 to Register a new user.
2. I get a "Registration Error".  

Console Log Output:
[ERROR] 56:23.730 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties. 
            Did you run `amplify push` after adding auth via `amplify add auth`?
            See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information
        ConsoleLogger.js:97
error signing up: NoUserPoolError: Authentication Error
    AuthError Errors.js:34
    NoUserPoolError Errors.js:50
    node_modules chat-bundle.js:1990
    node_modules chat-bundle.js:274
    _callee2$ AuthProvider.jsx:40
    Babel 8
    onRegister LoginWithCognito.jsx:21
    React 14
    unstable_runWithPriority scheduler.development.js:468
    React 4
        runWithPriority$1
        discreteUpdates$1
        discreteUpdates
        dispatchDiscreteEvent

**Expected behavior**
I expected to be able to successfully register a new user.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 11.6.2
 - Browser Firefox 
 - Version 91.4.0esr

**Comment by michhyun1** [comment]
@albrich-me Has your cloudformation stack been created successfully?

If so, have you completed these steps: https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat#running-the-amazon-chime-sdk-chat-demo

**Comment by michhyun1** [comment]
Please double check the src/Config.js file to see that the fields are correctly copied from the cloudformation stack before you run `npm install && npm run start`
