### ISSUE TITLE
Sign in failed

### ISSUE THREAD

**Issue by sagarpatel288** [aws-samples/amazon-chime-sdk#156]
**Demo**
Specify the name of the demo that you encountered the bug.
Chat Android Demo App

**Describe the bug**
We have updated `amplifyconfiguration.json` for following values:
1. `PoolId` for both `CredentialsProvider` and `CognitoUserPool`.
2. `AppClientId`
3. We have registered a user in cognito.
4. When we try to sign in with the same user via Android Chat Demo Application, we are getting sign in failed error with status code 200.

**To Reproduce**
1. Go to 'SignInActivity'
2. Click on 'Sign In'
4. See error: Sign in failed

**Expected behavior**
If we have already registered the user in Cognito and we are using the same username and password, clicking on sign in should successfully sign in the user.

**Screenshots**
![image](https://user-images.githubusercontent.com/11241767/153909127-de81b419-a99a-4dfb-a185-a406ec95f0ca.png)
![headers](https://user-images.githubusercontent.com/11241767/153909981-b0da6330-324e-4556-9701-38158d645e67.png)
![appHeaders](https://user-images.githubusercontent.com/11241767/153910335-39b817d2-c619-4003-82ad-48233453a7f2.png)
![image](https://user-images.githubusercontent.com/11241767/153910545-1948c370-aa29-42b0-a4f0-ced2febf2ea1.png)
![image](https://user-images.githubusercontent.com/11241767/153911150-8720b599-da44-4170-9841-7ef004364a3b.png)
![image](https://user-images.githubusercontent.com/11241767/153915366-76795952-c6bf-4b57-bb2e-c1a30b36de96.png)

**Smartphone (please complete the following information):**
 - Device: [Android]
 - OS: [11]

**Additional context**

**Comment by xuesichao** [comment]
Hi @sagarpatel288 , thanks for reporting this issue, I pinged our team to take a look at this issue. They should come back here later.

**Comment by ziyiz-amzn** [comment]
@sagarpatel288 Thank you for reporting. 
Will the same username/password work on js or iOS demo apps? 
Besides amplifyconfiguration.json, you will also need to update [AppConstants.kt](https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/chat-android/app/src/main/java/com/amazonaws/services/chime/sdkdemo/common/AppConstants.kt#L22-L23)

A detail-oriented blog post will explain all steps to set it up. https://aws.amazon.com/blogs/business-productivity/build-chat-applications-in-ios-and-android-with-amazon-chime-sdk-messaging/

**Comment by ziyiz-amzn** [comment]
Please feel free to leave comment if any issue. closing it now.
