### ISSUE TITLE
I get this error when trying to use the demo

### ISSUE THREAD

**Issue by jaybarnes** [aws-samples/amazon-chime-sdk#188]
If you try to use the cognito user pools option, clicking on the registration button pops up a dialog that says "Registration Failed." although the Lambda function-backed option works

ERROR in /Users/username/Documents/code/amazon-chime-sdk/apps/chat/src/containers/MeetingJoinDetails.tsx
./src/containers/MeetingJoinDetails.tsx 36:15-20
[tsl] ERROR in /Users/username/Documents/code/amazon-chime-sdk/apps/chat/src/containers/MeetingJoinDetails.tsx(36,16)
      TS2571: Object is of type 'unknown'.
 @ ./src/views/DeviceSetup/index.tsx 3:0-69 9:24-42
 @ ./src/Chat.jsx 16:0-46 31:96-107
 @ ./src/index.js 5:0-26 10:52-56

webpack 5.72.0 compiled with 1 error in 11063 ms

**Comment by jaybarnes** [comment]
I figured out the problem with "registration failed" -- I had assumed I could click on "Register" to go to a registration page, but the front page is also a registration page.

I didn't get specific failure feedback when I provided a password that didn't meet the listed requirements -- same registration failed message as clicking "register"

I don't believe this is associated with the pasted error message above, that might be something else.

**Comment by simmkyu** [comment]
## TypeScript errors

I can reproduce TypeScript errors, including the following, when I deleted `package-lock.json` and installed the latest dependencies specified in `package.json`.

```
% cd apps/chat
% rm -rf package-lock.json
% npm install
% npm start

// TypeScript errors
ERROR in /Users/username/Documents/code/amazon-chime-sdk/apps/chat/src/containers/MeetingJoinDetails.tsx
...
TS2571: Object is of type 'unknown'.
...
```

If I keep using the [exact version of `package-lock.json`](https://github.com/aws-samples/amazon-chime-sdk/blob/a475c387749fb0b2c347825d120567dd6b75c979/apps/chat/package-lock.json) from the repository, the demo works okay without any error. Please use the `package-lock.json` until the Chime SDK team looks into TypeScript failures.

⠀

---

## Sign up and sign in

> I figured out the problem with "registration failed" -- I had assumed I could click on "Register" to go to a registration page, but the front page is also a registration page.

Yes, you should do the following steps.

1. Ensure that you specify your deployed resources in `apps/chat/src/Config.js`.
1. Start the demo app.
   ```
   npm install
   npm start
   ```
1. On the entry page, fill **User name** and **Password** fields.
1. Choose **Register**.
1. If you see the following message, go to the [Amazon Cognito console](https://us-east-1.console.aws.amazon.com/cognito/home?region=us-east-1).
   > Your registration information has been set to your administrator. Contact them for additional instructions.
1. Choose your user pool and confirm the user.
   <img width="1168" alt="image" src="https://user-images.githubusercontent.com/36240708/162300134-f0a4d8df-6b36-48f5-abb1-390b40532594.png">
1. Once you see this message on the entry page, you can sign in to the demo using your account.
   > Your account is activated! Please sign in again to confirm.

⠀

---

## Suggestion

In production, I recommend using the AWS Amplify UI's Authenticator component.
https://ui.docs.amplify.aws/components/authenticator

The Authenticator component offers the user interfaces for sign in and sign up. You can integrate the Authenticator with The Amazon Cognito user pool that you deployed with the chat demo.
