### ISSUE TITLE
The state of the objects is not being updated

### ISSUE THREAD

**Issue by spuertab** [aws-samples/amazon-chime-sdk#192]
Looks like the state of the objects is not being updated in this part
https://github.com/aws-samples/amazon-chime-sdk/blob/26a127e6cbbf735a932c028d104222da03528d42/apps/chat/src/containers/input/Input.jsx#L83

Should it be like this?
const eventHandlerWithDebounce = React.useCallback(debounce(eventHandler, 500), [activeChannel, member]);
Instead of 
const eventHandlerWithDebounce = React.useCallback(debounce(eventHandler, 500), []);

**Comment by LeviSklaroff** [comment]
This callback is to indicate a user in the chat room is typing, and is supposed to be called when text is edited [here](https://github.com/aws-samples/amazon-chime-sdk/blob/26a127e6cbbf735a932c028d104222da03528d42/apps/chat/src/containers/input/Input.jsx#L86). 

- Is this behavior not working for you?
- If so could you please provide console logs for both the user typing and a second user in the same channel room.
