### ISSUE TITLE
Sample apps using aws-chime-sdk-js V3?

### ISSUE THREAD

**Issue by gravi2** [aws-samples/amazon-chime-sdk#204]
**Demo**
chat app

**Describe the bug**
I was trying to use the demo apps with latest V3 versions of AWS chime SDK. Are there examples that are compatible?

**Comment by xuesichao** [comment]
Hi @gravi2 , I assume the "latest V3 versions of AWS chime SDK" you mentioned refers to `amazon-chime-sdk-js`. If so you can refer to our [browser demo](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser). 

Else if you were talking about the `amazon-chime-sdk-component-library-react`, you can refer to our [meeting demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting).

If you were talking about the [chat demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat), unfortunately we haven't migrated this demo to V3.

**Comment by gravi2** [comment]
@xuesichao Thanks for the followup. I meant the versions of `amazon-chime-sdk-j`s and `amazon-chime-sdk-component-library-react` used in the chat demo app.  

I have raised a PR #205 to upgrade the chat demo app. Please take a look.

**Comment by ltrung** [comment]
Thank @gravi2. We have merged the PR so close the issue.
