### ISSUE TITLE
Invalid region error for chat app

### ISSUE THREAD

**Issue by kalyanidz** [aws-samples/amazon-chime-sdk#207]
**Demo**
Chat app

**Describe the bug**
Chat app throws "invalid region" error with cognito user pool and S3 bucket in AWS US-east-2 region. 

**To Reproduce**
1. Go to amazon-chime-sdk/apps/chat/src/Config.js
2. Update cognito user pool details with user pool in region us-east-2
3. Specify _apiGatewayInvokeUrl_ as local express app hosting url to create meeting.
4. Login to the application
5. Console shows error "invalid region" error. 

```
event_listeners.js:97 Uncaught (in promise) ConfigError: Invalid region in config
    at Request.VALIDATE_REGION (event_listeners.js:97:1)
    at Request.callListeners (sequential_executor.js:106:1)
    at callNextListener (sequential_executor.js:96:1)
    at event_listeners.js:86:1
    at finish (config.js:396:1)
    at config.js:414:1
    at Credentials.get (credentials.js:127:1)
    at getAsyncCredentials (config.js:408:1)
    at Config.getCredentials (config.js:428:1)
    at Request.VALIDATE_CREDENTIALS (event_listeners.js:81:1)
```

6. After getting this error, we changed cognito user pool details with user pool in region us-east-1. But still getting the same error.

**Expected behavior**
Chime SDK should be able to connect with users from all region, exactly the way Amazon Chime Application works for all regions.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser - Chrome

**Comment by duh17** [comment]
Chime Messaging SDK currently only supports "us-east-1" and "eu-central-1" region.  Although It is possible to connect to a cognito user pool and S3 bucket in a different region. However that requires you to handle cross-region calls and updating the different dependencies required for your use case. This is not something we officially support today, but we are in the process of planning for additional regions support. 

For available regions for Chime SDK you can reference here:
https://docs.aws.amazon.com/chime-sdk/latest/dg/sdk-available-regions.html

**Comment by kalyanidz** [comment]
> Chime Messaging SDK currently only supports "us-east-1" and "eu-central-1" region. Although It is possible to connect to a cognito user pool and S3 bucket in a different region. However that requires you to handle cross-region calls and updating the different dependencies required for your use case. This is not something we officially support today, but we are in the process of planning for additional regions support.
> 
> For available regions for Chime SDK you can reference here: https://docs.aws.amazon.com/chime-sdk/latest/dg/sdk-available-regions.html

Thank you for the reply
