### ISSUE TITLE
Low audio and no echo cancellation on android devices

### ISSUE THREAD

**Issue by mansoorakhtaricp** [aws-samples/amazon-chime-sdk#233]
We have configured aws chime meeting demo mentioned below and its working perfectly except we have only audio issue on android devices.

https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting 

The meeting audio is working fine only on desktop, but when someone connect from android device then we have low audio from there side also there is no echo cancellation (i-e Echo back issue) , we have also experienced audio issue using Bluetooth, hands-free in android device.  

**To Reproduce**
1. Go to deployed demo from desktop and join meeting there
2. Then join same meeting from android device [we have tested with Galaxy Note 8 Google Chrome, the issue is also on other android devices as well]
3. You will experience the voice focus issue and echo back issue. even echo cancellation is enabled but its not working for android device.
![and-device-issue](https://user-images.githubusercontent.com/113033607/188891104-2797a434-066d-4bd1-9577-5b013a166e9a.png)

**Comment by xuesichao** [comment]
Hi @mansoorakhtaricp, I removed your deployed demo URL in the description to protect your resources.

For your question, from our doc: https://aws.github.io/amazon-chime-sdk-js/modules/amazonvoice_focus.html#browser-compatibility

>Amazon Voice Focus and Echo Reduction are more CPU-intensive than conventional noise suppression systems, and the web runtime affects performance. As such, not all mobile devices or lower-spec laptop or desktop computers will be sufficiently powerful, or will be able to use Amazon Voice Focus and Echo Reduction while also supporting multiple video streams and rich application functionality.
>
>The default configuration will adapt to available processor power and adjust quality accordingly, but some browsers and devices will simply be unable to enable the feature. Android browsers are theoretically compatible, but typically cannot meet the performance requirements. iOS 14 ships Safari 14, and relatively modern iPhones (e.g., iPhone X) have been found to be fast enough.

**Comment by xuesichao** [comment]
Close due to inactivity.
