### ISSUE TITLE
y-chime-messaging is not exists in npm any more

### ISSUE THREAD

**Issue by RohitKumarAlgo** [aws-samples/amazon-chime-sdk#239]
Hi Team,
I have cloned the repo URL and followed all the steps written in this blog [https://aws.amazon.com/blogs/business-productivity/real-time-collaboration-using-amazon-chime-sdk-messaging/](url) But still, after running the project I m getting the following issue

```
**ERROR in /home/rohit/amazon-chime-sdk/apps/real-time-collaboration/examples/text-editor/src/index.ts(15,8)
      TS2307: Cannot find module 'y-chime-messaging' or its corresponding type declarations.**

```
So basically it cannot find the required NPM named "y-chime-messaging". I have also searched on NPM to find this but am unable to find it. Can you please guide me on how can I resolve this issue? or which alternative NPM i can use?

**Comment by devalevenkatesh** [comment]
Hi @RohitKumarAlgo , so this is a demo where `y-chime-messaging` is a private package and the dependencies are managed by `lerna`. `y-chime-messaging` is not published to NPM hence you wont find any such package in NPM. The error you are seeing is something related to `typescript` and I believe not to NPM.

I cloned the repo freshly and did the same steps as mentioned in README below and it works:
https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/real-time-collaboration

Could you please follow the README step by step and let us know if there is any issue?

Are you just trying to run the `real-time-collaboration` demo or using is somewhere else?
Are you making any changes to `tsconfig.json` inside the demo?
What is your typescript version?

**Comment by RohitKumarAlgo** [comment]
Hi @devalevenkatesh  Let me retry again and get back to you!

**Comment by RohitKumarAlgo** [comment]
Hi @devalevenkatesh It's working fine now on local but the issue I m still facing is that after even hosting on AWS S3 as a static hosting website it's not working its just show random small tabs. 
Can you help me out here?

**Comment by RohitKumarAlgo** [comment]
Hi, @devalevenkatesh It's now successfully running on the local. But when I m trying to host the same on AWS S3 bucket as static website hosting it's not working.
I have uploaded the entire real-time-collaboration folder along with node_moudules/ and given the path for the index.html but still its not working as expected. Can you please guide me here how can I host the same?
