### ISSUE TITLE
Chime SDK Messaging responds "Channel Messages size limit exceeded." when pasting long text.

### ISSUE THREAD

**Issue by yoshitsugu** [aws-samples/amazon-chime-sdk#247]
**Demo**
real-time-collaboration

**Describe the bug**
Maybe it's not required quality for demo, but real-time-collaboration editor cannot sync long text(maybe 4096 characters~?)

**To Reproduce**
1. start Quill editor following [README](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/real-time-collaboration#getting-started)
2. Open editor on any browser.
3. Copy and Paste long text (like 4096 "a" chars)
4. See "Channel Messages size limit exceeded" error from Chime messaging API, and text content is not synced.

**Expected behavior**
- Sync long text correctly

**Screenshots**
![Screenshot from 2022-11-04 09-59-04](https://user-images.githubusercontent.com/748445/199862654-9578b621-6020-4efe-b4cb-8fb14fd76d15.png)

**Desktop (please complete the following information):**
 - OS: Linux(Arch Linux)
 - Browser: Chrome
 - Version: 107.0.5304.87

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ssorren** [comment]
@yoshitsugu This is expected behavior. The content is limited to 4kb for SendChannelMessage : 

https://docs.aws.amazon.com/chime/latest/APIReference/API_SendChannelMessage.html

**Comment by yoshitsugu** [comment]
@ssorren got it. thank you!
