### ISSUE TITLE
Can't launch the chat demo app

### ISSUE THREAD

**Issue by i-soroka** [aws-samples/amazon-chime-sdk#26]
**Demo**
Can't launch the chat app

**Describe the bug**
I followed to the tutorial: installed AWS CLI, deployed Amazon Cloudformation template, installed npm modules. But when I run the app (npm start) it stucks on this phasee (see screenshot) and nothing is loaded when I'm trying to open http://localhost:3000 or http://localhost:9000

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10 x64
 ![Screenshot](https://i.ibb.co/pZQgkBz/stuck.png)

**Comment by mealbarracin10** [comment]
Project is running at https://0.0.0.0:9000/
try to open : https://0.0.0.0:9000/
