### ISSUE TITLE
televisit-demo - frontend deployment failure (ERESOLVE unable to resolve dependency tree)

### ISSUE THREAD

**Issue by koba206** [aws-samples/amazon-chime-sdk#295]
**Demo**
Specify the name of the demo that you encountered the bug.

televisit-demo

**Describe the bug**

When I run ./deploy.sh, I get an error on processing the frontend side deployment.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: chime-sdk-chat-demo@1.0.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@">=16.8.6" from @chakra-ui/icons@1.0.5
npm ERR!   node_modules/@chakra-ui/icons
npm ERR!     @chakra-ui/icons@"1.0.5" from the root project
npm ERR!   2 more (@emotion/react, @emotion/styled)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=18" from @chakra-ui/system@2.5.2
npm ERR! node_modules/@chakra-ui/system
npm ERR!   peer @chakra-ui/system@">=1.0.0" from @chakra-ui/icons@1.0.5
npm ERR!   node_modules/@chakra-ui/icons
npm ERR!     @chakra-ui/icons@"1.0.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/ec2-user/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2023-03-22T19_44_37_352Z-debug-0.log
```

**To Reproduce**
1. Clone the repository
2. cd apps/televisit-demo
3. ./deploy.sh

**Expected behavior**

Successful deployment

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac iTerm (I also tried with AWS CloudShell and Cloud9 but same result)

**Additional context**
I also tried to manually go to frontend directory and initiate npm install, but received same exact error.

**Comment by nslusher-sf** [comment]
Changing icons to `"@chakra-ui/icons": "^1.1.7",` and adding the line `"@chakra-ui/system": "^1.6.7",` to the dependencies block allowed me to complete an install though I haven't been able to test yet if the full demo works.

**Comment by michhyun1** [comment]
Can you please check this github issue: https://github.com/chakra-ui/chakra-ui/issues/7491

That should resolve your issue
