### ISSUE TITLE
[Chime SDK React Component Library] [Voice Focus] Sound Breaking, glitcher when using Voice Focus 

### ISSUE THREAD

**Issue by Lelvu** [aws-samples/amazon-chime-sdk#314]
**Demo**
Current, our team are  to develop the Web App using **Chime SDK React Component Library** and we faced the critical issue related to sound breaking
Our team has developed following this sample :[React Meeting Demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting) 

**Describe the bug**
There is an breaking sound - glitcher audio issue when we turning on Voice Focus, this issue are reported from our AWS supporting side. They tried these steps

They used iOS 16.2 Simulator and the React Meeting Demo from [React Meeting Demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting) to reproduce the following steps:
> 1. Launch iOS 16.2 Simulator, access React Meeting Demo.  
>2. With the WebAudio ON, select Mock audio device 1, and enter the room.  
>3. Join the meeting with another device (at this point, the sound can be heard normally).  
>4. Turn on VoiceFocus on iOS 16.2 Simulator (there will be sound issues, and the sound may be unclear or completely muted by VoiceFocus).  
>5. Turn off VoiceFocus on iOS 16.2 Simulator (the sound issue persists even after turning off VoiceFocus).

**To Reproduce**
Our team also follow the recommend above and can reproduce it by following.
1. Follow this guideline to run the sample: [React AWS Meeting Sample](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting) 
	1. Install homebrew : `brew install nvm`
	2. Install node 16 :  `nvm install 16`
	3. Run   `yarn start:fast`
	4. Access to .  [https://10.253.13.135:9000](https://10.253.13.135:9000/) using same local network
2. `Device_AListen` access meeting with the meetingID ( only select on Enable Web Audio )
3. `Device_BSpeak` join meeting with same meetingID ( only select on Enable Web Audio )
At this time, both device can hear clearly
4. `Device_BSpeak` enable Voice focus and speak
At the moment, there is an issue with the sound. The sound is either unclear or breaking due to VoiceFocus.
5. `Device_BSpeak` turn off Voice focus and speak
The issue at no.4 still happen.

**Smartphone**
DEVICE COMBINATION THAT CAN REPRODUCE
Notice that this issue only happen in some device OS and not happen on others.

| Device_AListen | Device_BSpeak |
|---|---|
| iPhone 12PRO_16.3(20D47) | iPhone11_16.3.1(20D67) |
| iPhone11_16.3.1(20D67) | iPhone 12_PRO_16.3(20d47) |
| iPhone13_16.4.1(20E252) | iPhoneXR_15.4.1(19258) |

**Expected behavior**
The audio can hear clearly without sound breaking.

**Screenshots**
no screen shot but will provide the audio recording.

**Additional context**
1. Our team also search several AWS related form post [Voice Focus Issue in Chime SDK](https://github.com/aws/amazon-chime-sdk-js/issues/2609) but it also don't see any way to solve it yet
2. Noticed that our team also tried on other devices, and we found that the issue CANNOT REPRODUCE with these combination

| Device_AListen | Device_BSpeak |
|---|---|
| iPhoneXR_15.4.1(19E28) | iPhoneXsMax_15.4.1(19E28) |
| iPhone11_16.3.1(20D27) | iPhoneXR_15.4.1(19E28) |
| iPhoneXR_15.4.1(19E258) | iPhone13_16.4.1(20E252) |

**Comment by devalevenkatesh** [comment]
Keeping the main issue https://github.com/aws/amazon-chime-sdk-js/issues/2609 open and closing as duplicates.
