### ISSUE TITLE
Chime SDK for JS keeps getting "Websocket close"

### ISSUE THREAD

**Issue by christo-pr** [aws-samples/amazon-chime-sdk#336]
**Demo**
[amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js/tree/main)

**Describe the bug**
I've setup a React app with almost the same code of the example for the web chat chime sdk, and it works fine, but for some reason we keep getting a lot of `Websocket close` event, it does have a status code, but it doesn't show any reason

**To Reproduce**
1. Use the example code to setup a messaging service 
2. Open a connection with a chime client
3. See error

**Expected behavior**
I would expect probably 1 disconnect or 2, but sometimes it just stays there for like 1min until it finally get a last `SESSION_ESTABLISHED` message and everything works fine. It would also be helpful to know what does the error 4005 means, not sure if there's a missing configuration that causes this

**Screenshots**
![image](https://github.com/aws-samples/amazon-chime-sdk/assets/14341735/8e59fab4-92ad-4ed7-adff-679d508a27c1)

**Desktop (please complete the following information):**
 - OS: IOS - 13.3.1 (22E261)
 - Browser Chrome -  V114.0.5735.198 (Official Build) (arm64)

**Additional context**
Worth to mention that is not always like that, sometimes it works fine the first time, sometimes it takes sometimes, but mostly of the times is closing the Websocket

**Comment by martiz23** [comment]
I have the same issue, this happens to me when i connect to the socket from diffferent places with the same user.

**Comment by christo-pr** [comment]
@martiz23  I forget I opened an issue here, for my it was a react re-render issue, I had the effect that initialize the chat service running twice, which make this behavior to show, I'd say just verify that and probably you'll get it fix it too
