### ISSUE TITLE
When someone does a screen share, they see a recursive view of their client screen and so do the other users

### ISSUE THREAD

**Issue by dschueler** [aws-samples/amazon-chime-sdk#44]
**Demo**
amazon-chime-sdk/apps/meeting/

**Describe the bug**
When someone shares their screen from the client...what everyone sees is a "recursive" stack of windows. Very annoying. 

**To Reproduce**
Just start a meeting and do a screen share

**Expected behavior**
Really the "screen" part of both clients should not jointly show the shared screen. If one side or the other shares their screen, that side should hide that canvas part of their client....if the other clients actually do receive an event notification for the screen share from another user then it should show that canvas

**Screenshots**
<img width="913" alt="2021-08-24_07-06-01" src="https://user-images.githubusercontent.com/371030/130610321-8600a129-cbc8-4d62-a698-766d8cd21b5a.png">

**Desktop (please complete the following information):**
same behavior on all systems and browsers 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dschueler** [comment]
The above recursive stack is what everyone sees.

**Comment by ltrung** [comment]
This is a duplicate question to https://github.com/aws/amazon-chime-sdk-js/issues/293.
In summary, this is an expected behavior if you have shared the entire screen or the browser window displaying your own screen share. One solution is to hide the screen share from your app while sharing your screen. i.e. Display other's screen only.

**Comment by dschueler** [comment]
It would be nice if that was the default built into the app. The Chime APP itself handles it this way I believe.

**Comment by ltrung** [comment]
@dschueler I think you can workaround this behavior by not showing the screenshare in the sharer's view to prevent the mirror effect that causes this. This can be done in videoTileDidUpdate to skip binding the sharer content share.
```
videoTileDidUpdate(tileState: VideoTileState): void {
  if (tileState.isContent) {
      const isSelfAttendee =
        new DefaultModality(tileState.boundAttendeeId).base() ===
        this.meetingSession.configuration.credentials.attendeeId;
      if (isSelfAttendee) {
        return;
      }
    }
}
```

**Comment by amiller5bf** [comment]
@ltrung where would that be placed in the project? For example, Don and I are using /apps/meeting structure as our base. We haven't changed the skeleton much at all. Not sure which file I need to drop that into.
