### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by Roberto75** [aws-samples/amazon-chime-sdk#46]
**Demo**
chime-sdk-meeting-demo@0.1.0

**Describe the bug**
build errors 

**To Reproduce**
1.In the root directory apps/meeting, run npm install
2. run    npm start
3. See error

TS2305: Module '"../node_modules/amazon-chime-sdk-component-library-react/lib"' has no exported member 'VoiceFocusProvider'.

 TS2724: Module '"../../../node_modules/amazon-chime-sdk-component-library-react/lib"' has no exported member 'AudioInputVFControl'. Did you mean 'AudioInputControl'?

**Screenshots**
![image](https://user-images.githubusercontent.com/8872875/131116060-a0f8a13a-7fc3-4b20-a2c3-b1ec07e54480.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - npm: 7.21.1
 - node: 12.13.1

**Additional context**
any local changes

**Comment by ltrung** [comment]
NPM `amazon-chime-sdk-component-library-react` 2.9.0 has been released and should fix this issue.
