### ISSUE TITLE
Recording audio and video not in sync

### ISSUE THREAD

**Issue by SuhailHassan** [aws-samples/amazon-chime-sdk#54]
While recording the audio video call, sometimes audio and video are not in sync. Few seconds of lag is there

**Comment by simmkyu** [comment]
Which demo in the [Amazon Chime SDK Samples repository](https://github.com/aws-samples/amazon-chime-sdk) were you using to record the audio-video call?

- If you were using the [Amazon Chime SDK recording repository](https://github.com/aws-samples/amazon-chime-sdk-recording-demo), could you please create an issue in their repository?
  https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues
- If you were using the [CreateMediaCapturePipeline](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMediaCapturePipeline.html) API action in one of our demos, could you provide us with the following information?
   - SDK version
   - Browser
   - Reproduction steps
   - Meeting ID and attendee ID
   - INFO-level browser logs

**Comment by xuesichao** [comment]
Close the issue due to no response.
Feel free to reopen it.
