### ISSUE TITLE
Bug on livereload

### ISSUE THREAD

**Issue by Brenerss** [aws-samples/amazon-chime-sdk#80]
In the current amazon chime project, where the meeting folder is now separate, live reloading doesn't work, we need to restart the server all the time

**Comment by xuesichao** [comment]
Hi @Brenerss , thanks for reporting this issue, I confirm it exists. After making some changes, the App reloads infinitely. Will look into this issue and post the update here.

**Comment by Brenerss** [comment]
Ok, thanks

**Comment by xuesichao** [comment]
Merged the fix to meeting-dev branch. The fix will be merged into main branch after next release.
