### ISSUE TITLE
InvalidSignatureException: Credential should be scoped to correct service: 'execute-api'.  [AWS][CHIME]

### ISSUE THREAD

**Issue by dorapax-lab** [aws-samples/amazon-chime-sdk#91]
**Demo**
[Monitoring and troubleshooting with amazon chime sdk meeting events](https://aws.amazon.com/blogs/business-productivity/monitoring-and-troubleshooting-with-amazon-chime-sdk-meeting-events/)

**Describe the bug**
I am getting below error when trying create a meeting.
```
InvalidSignatureException: Credential should be scoped to correct service: 'execute-api'. 
```

**To Reproduce**
1. Get an endpoint url by following these steps. [https://aws.amazon.com/blogs/business-productivity/monitoring-and-troubleshooting-with-amazon-chime-sdk-meeting-events/](https://aws.amazon.com/blogs/business-productivity/monitoring-and-troubleshooting-with-amazon-chime-sdk-meeting-events/) 
2. Set endpoint url in your node js server with aws chime sdk
```
AWS.config.credentials = new AWS.Credentials(
  process.env.ACCESS_KEY_ID,
  process.env.SECRET_ACCESS_KEY,
  null
)

const chime = new AWS.Chime({
  region: 'us-east-1',
})

const endpoint = process.env.ENDPOINT
chime.endpoint = new AWS.Endpoint(endpoint)

const meetingTable[title] = await chime
      .createMeeting({
        ClientRequestToken: uuidv4(),
        MediaRegion: req.query.region,
        ExternalMeetingId: title.substring(0, 64),
      })
      .promise()
```

**Expected behavior**
Meeting should be created successfully.

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Postman

**Smartphone (please complete the following information):**
 - Device: Huawei GR 5
 - OS: Android

**Additional context**
When I used global endpoint (https://service.chime.aws.amazon.com) this works fine. Problem with my own endpoint created with demo.

**Comment by hokyungh** [comment]
Sounds like you are passing your own url to `chime.endpoint = new AWS.Endpoint(endpoint)`?
Did you pass your own demo url?

**Comment by jing-chen1** [comment]
Closing it, feel free to reopen it if you still have problems.
