### ISSUE TITLE
How to send a image message use [app]-messaging-sdk

### ISSUE THREAD

**Issue by ThunderLi** [aws-samples/amazon-chime-sdk#92]
I want to send a image use chimeMessagingSDK in app, but i dont know how to do.

**Comment by ziyiz-amzn** [comment]
Hi @ThunderLi Could you please refer to the iOS chat demo app? It includes the attachment feature in the demo. 
https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat-ios

Thanks!
